export const CARS_REQUEST = 'CARS_REQUEST'
export const CARS_SUCCESS = 'CARS_SUCCESS'
export const CARS_FAILED = 'CARS_FAILED'

export const FILTERS_LOAD = 'FILTERS_LOAD'
export const FILTERS_REQUEST = 'FILTERS_REQUEST'